// Generated by CoffeeScript 1.4.0
(function() {

  require.config({
    paths: {
      kinetic: "lib/kinetic-v4.3.0"
    }
  });

  require(["simpleGame"], function(SimpleGame) {
    return new SimpleGame("container");
  });

}).call(this);
