// Generated by CoffeeScript 1.4.0
(function() {

  define(["kinetic"], function(Kinetic) {
    var Game;
    Game = (function() {

      function Game(containerId, _width, _height) {
        this._width = _width != null ? _width : 800;
        this._height = _height != null ? _height : 600;
        this._stage = new Kinetic.Stage({
          container: containerId,
          width: this._width,
          height: this._height
        });
        this.showScreen(this._getInitialScreen());
      }

      Game.prototype._getInitialScreen = function() {
        throw new Error("Cannot invoke abstract method Game._getInitialScreen.");
      };

      Game.prototype.showScreen = function(screen) {
        return this._stage.add(screen.getLayer());
      };

      Game.prototype.hideScreen = function(screen) {
        return screen.remove();
      };

      Game.prototype.getWidth = function() {
        return this._width;
      };

      Game.prototype.getHeight = function() {
        return this._height;
      };

      return Game;

    })();
    return Game;
  });

}).call(this);
